image: registry.gitlab.com/quorumsco/dev-ops/docker-images/frontend-team/docker:20.10.21

stages:
  - upload

services:
  - docker:20.10.21-dind

upload-embed:
  stage: upload

  rules:
    - changes:
        - qomon.zip
    - when: manual
      # variables:
      #   DOPPLER_TOKEN: $DOPPLER_TOKEN_PROD

  variables:
    DOPPLER_TOKEN: $DOPPLER_TOKEN_INTE

  before_script:
    # Retrieve variables from doppler according env
    - apk add --no-cache curl gnupg
    - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
    - export BUCKET_NAME=$(doppler secrets get BUCKET_NAME --plain)
    - export AWS_ACCESS_KEY_ID=$(doppler secrets get AWS_ACCESS_KEY_ID --plain)
    - export AWS_SECRET_ACCESS_KEY=$(doppler secrets get AWS_SECRET_ACCESS_KEY --plain)
    # Setup aws with credentials
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region fr-par

  script:
    - pnpm install
    - pnpm plugin-zip
    - aws --endpoint-url https://s3.fr-par.scw.cloud s3 cp ./qomon.zip s3://$BUCKET_NAME/plugin/v1/qomon.zip --metadata-directive REPLACE --acl public-read --cache-control no-cache
